[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid
[program:php]
command=php-fpm -F
autorestart=false
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
[program:nginx]
command=nginx -g "daemon off;"
autorestart=false
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
[eventlistener:exit]
command=/usr/local/bin/happyro-exit-listener
events=PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
priority=1
