"""Generate the client runtime card-name overlay from the canonical catalog."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[3]
items = json.loads((root / 'repos/happyro-admin/backend/resources/game-data/items/client-kro-20211105.json').read_text())['items']
server_items = json.loads((root / 'repos/happyro-admin/backend/resources/game-data/items/renewal.json').read_text())['items']
overrides = {
    item_id: item['names']['zh-CN']
    for item_id, item in items.items()
    if server_items.get(item_id, {}).get('Type') == 'Card'
    and str(item.get('names', {}).get('zh-CN', '')).endswith('卡片')
}
output = root / 'repos/happyro-client/src/DB/Items/CardNameOverrides.generated.js'
output.write_text(
    '// Generated by tools/resources/catalog/generate_card_overrides.py. Do not edit manually.\n\n'
    f'export default {json.dumps(overrides, ensure_ascii=False, separators=(",", ":"))};\n',
    encoding='utf-8',
)
print(f'generated {len(overrides)} card name overrides')
