"""Generate client runtime item-name overrides from the canonical catalog."""
import json
import sys
from pathlib import Path


def usage(color: bool = True) -> None:
    def paint(code: str, value: str) -> str:
        return f"\033[{code}m{value}\033[0m" if color else value

    print(
        f"\n{paint('1;36', 'HappyRO item name override generator')}\n\n"
        f"{paint('1;33', 'Usage')}\n"
        f"  {paint('1;32', 'python3 generate_item_name_overrides.py --write')} [--no-color]\n\n"
        f"{paint('1;33', 'Examples')}\n"
        f"  {paint('36', 'python3 generate_item_name_overrides.py --write')}\n"
        f"  {paint('36', 'python3 generate_item_name_overrides.py --write --no-color')}\n"
    )


def main(arguments: list[str]) -> int:
    color = "--no-color" not in arguments
    if not arguments or arguments == ["--no-color"] or any(argument in {"-h", "--help"} for argument in arguments):
        usage(color)
        return 0
    unknown = set(arguments) - {"--write", "--no-color"}
    if unknown or "--write" not in arguments:
        raise SystemExit(f"Unknown or incomplete arguments: {' '.join(arguments)}")

    root = Path(__file__).resolve().parents[3]
    catalog = json.loads(
        (root / "repos/happyro-admin/backend/resources/game-data/items/client-kro-20211105.json").read_text()
    )
    items = catalog["items"]
    client_items = json.loads((root / catalog["clientSource"]["path"]).read_text())["data"]
    overrides = {
        item_id: item["names"]["zh-CN"]
        for item_id, item in items.items()
        if item["names"]["zh-CN"] != client_items[item_id]["identifiedDisplayName"]
    }
    output = root / "repos/happyro-client/src/DB/Items/ItemNameOverrides.generated.js"
    output.write_text(
        "// Generated by tools/resources/catalog/generate_item_name_overrides.py. Do not edit manually.\n\n"
        f"export default {json.dumps(overrides, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"generated {len(overrides)} item name overrides")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
